name: Upload Godot release
description: Upload the Godot release.
inputs:
  name:
    description: The release name.
    default: "${{ github.job }}"
runs:
  using: "composite"
  steps:
    - name: Upload Godot release
      uses: actions/create-release@v1
      id: create_release
      with:
        release_name: ${{ inputs.name }}
        tag_name: ${{ github.ref }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ github.token }}