name: Upload Godot release
description: Upload the Godot release.
inputs:
  name:
    description: The release name.
    default: "${{ github.job }}"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload Godot release
      uses: softprops/action-gh-release@v1
      with:
        files: "bin/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}