name: Upload Godot release
description: Upload the Godot release.
inputs:
  name:
    description: The release name.
    default: "${{ github.job }}"
runs:
  using: "composite"
  steps:
    - name: Upload Godot release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ inputs.name }}
        body: |
          testing release
          - Test
        draft: true
        prerelease: false